/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.List;

import com.ms.Address;
import com.ms.User;

public class App {
    public String getGreeting() {
        return "Hello, World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Address address1 = Address.newBuilder()
                .setStreet("123 Main St")
                .setCity("Anytown")
                .setState("CA")
                .setZipCode("12345")
                .build();

        Address address2 = Address.newBuilder()
                .setStreet("456 Elm St")
                .setCity("Othertown")
                .setState("NY")
                .setZipCode("67890")
                .build();

        User user = User.newBuilder()
                .setFirstName("John")
                .setLastName("Doe")
                .setEmail("jdoe@example.com")
                .addAllAddress(List.of(address1, address2))
                .build();

        System.out.println("User created: " + user.getFirstName() + " " + user.getLastName());
        System.out.println("Addresses:");
        for (Address address : user.getAddressList()) {
            System.out.println(" - " + address.getStreet() + ", " + address.getCity() + ", " + address.getState() + " "
                    + address.getZipCode());
        }
    }
}
